import { DiaGym } from '../models/ArrayGym.model';

const arraygym: DiaGym[] = [
  {
    dia: '1',
    ejercicios: [
      {
        tipoEjercicio: 'Pecho',
        nombreEjercicio: 'Press plano manc',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '25kg',
        masInformacion: 'En el gym de DT, le pongo 4 barritas',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Frances',
        tipoEjercicio: 'Tríceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Apertura plana manc 4x15',
        tipoEjercicio: 'Pecho',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '??',
        masInformacion: 'como 7 ladrillos',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Tríceps poleas',
        tipoEjercicio: 'Tríceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '??',
        masInformacion: 'como 8 ladrillos',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Pull over poleas',
        tipoEjercicio: 'Pecho',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Triceps Romana manc',
        tipoEjercicio: 'Tríceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Cortos',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x30',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Oblicuos',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x30',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
    ],
  },
  {
    dia: '2',
    ejercicios: [
      {
        nombreEjercicio: 'Tirones adelante abierto',
        tipoEjercicio: 'Espalda',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '50kg',
        masInformacion: 'como 10 ladrillos',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Alternado',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '15kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Remo 1 brazo manc',
        tipoEjercicio: 'Espalda',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '15kg??',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Concentrado',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '15kg??',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Dominadas',
        tipoEjercicio: 'Espalda',
        repiticionesYSeries: 'Al Fallo',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Tirones Supino',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '70kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Biceps polea',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '40kg',
        masInformacion: '6 o 7 ladrillos creo',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Abs completos',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x20',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Russian',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x30',
        pesoUtilizado: '15kg',
        masInformacion: '',
        imagenGif: '',
      },
    ],
  },
  {
    dia: '3',
    ejercicios: [
      {
        nombreEjercicio: 'Press manc ',
        tipoEjercicio: 'Hombros',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg??',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Cuádriceps',
        tipoEjercicio: 'Piernas',
        repiticionesYSeries: '4x15',
        pesoUtilizado: '60kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Vuelos lat 1 brazo',
        tipoEjercicio: 'Hombros',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '10kg??',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Isquios',
        tipoEjercicio: 'Piernas',
        repiticionesYSeries: '4x15',
        pesoUtilizado: '35kg??',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Vuelos frente poleas',
        tipoEjercicio: 'Hombros',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '25kg??',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Prensa',
        tipoEjercicio: 'Piernas',
        repiticionesYSeries: '4x8',
        pesoUtilizado: '50kg',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Abs bici',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x20',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Abs elevaciones',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x20',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Rueda',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x10',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
    ],
  },
];

export { arraygym };
