import { DiaGym } from '../models/ArrayGym.model';
const arraygym: DiaGym[] = [
  {
    dia: '1',
    ejercicios: [
      {
        tipoEjercicio: 'Pecho',
        nombreEjercicio: 'Press plano manc',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '25kg',
        masInformacion: '',
        imagenGif: 'Pecho/PressPlanoManc.gif',
      },
      {
        nombreEjercicio: 'Frances',
        tipoEjercicio: 'Tríceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg',
        masInformacion: '',
        imagenGif: 'Triceps/Frances.gif',
      },
      {
        nombreEjercicio: 'Apertura plana manc 4x15',
        tipoEjercicio: 'Pecho',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '??',
        masInformacion: 'como 7 ladrillos',
        imagenGif: 'Pecho/AperturaPlanaMancuerna.gif',
      },
      {
        nombreEjercicio: 'Tríceps poleas',
        tipoEjercicio: 'Tríceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '??',
        masInformacion: 'como 8 ladrillos',
        imagenGif: 'Triceps/TricepPolea.gif',
      },
      {
        nombreEjercicio: 'Pull over poleas',
        tipoEjercicio: 'Pecho',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg',
        masInformacion: '',
        imagenGif: 'Pecho/PulloverPoleas.gif',
      },
      {
        nombreEjercicio: 'Triceps Romana manc',
        tipoEjercicio: 'Tríceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg',
        masInformacion: '',
        imagenGif: 'Triceps/TricepsRomanaManc.gif',
      },
      {
        nombreEjercicio: 'Cortos',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x30',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Oblicuos',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x30',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: 'Abdominales/Oblicuos.gif',
      },
    ],
  },
  {
    dia: '2',
    ejercicios: [
      {
        nombreEjercicio: 'Tirones adelante abierto',
        tipoEjercicio: 'Espalda',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '50kg',
        masInformacion: 'como 10 ladrillos',
        imagenGif: 'Espalda/TironesAdelanteAbierto.gif',
      },
      {
        nombreEjercicio: 'Alternado',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '15kg',
        masInformacion: '',
        imagenGif: 'Biceps/Alternado.gif',
      },
      {
        nombreEjercicio: 'Remo 1 brazo manc',
        tipoEjercicio: 'Espalda',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '15kg??',
        masInformacion: '',
        imagenGif: 'Espalda/Remo1BrazoManc.gif',
      },
      {
        nombreEjercicio: 'Concentrado',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '15kg??',
        masInformacion: '',
        imagenGif: 'Biceps/Concentrado.gif',
      },
      {
        nombreEjercicio: 'Dominadas',
        tipoEjercicio: 'Espalda',
        repiticionesYSeries: 'Al Fallo',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: 'Espalda/Dominadas.gif',
      },
      {
        nombreEjercicio: 'Tirones Supino',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '70kg',
        masInformacion: '',
        imagenGif: 'Biceps/TironesSupino.gif',
      },
      {
        nombreEjercicio: 'Biceps polea',
        tipoEjercicio: 'Biceps',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '40kg',
        masInformacion: '6 o 7 ladrillos creo',
        imagenGif: 'Biceps/BicepsPolea.gif',
      },
      {
        nombreEjercicio: 'Abs completos',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x20',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Russian',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x30',
        pesoUtilizado: '15kg',
        masInformacion: '',
        imagenGif: 'Abdominales/Russian.gif',
      },
    ],
  },
  {
    dia: '3',
    ejercicios: [
      {
        nombreEjercicio: 'Press manc',
        tipoEjercicio: 'Hombros',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '7.5kg??',
        masInformacion: '',
        imagenGif: 'Hombros/PressMancuerna.gif',
      },
      {
        nombreEjercicio: 'Cuádriceps',
        tipoEjercicio: 'Piernas',
        repiticionesYSeries: '4x15',
        pesoUtilizado: '60kg',
        masInformacion: '',
        imagenGif: 'Piernas/Cuadriceps.gif',
      },
      {
        nombreEjercicio: 'Vuelos laterales',
        tipoEjercicio: 'Hombros',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '10kg??',
        masInformacion: '',
        imagenGif: 'Hombros/VuelosLaterales.gif',
      },
      {
        nombreEjercicio: 'Isquios',
        tipoEjercicio: 'Piernas',
        repiticionesYSeries: '4x15',
        pesoUtilizado: '35kg??',
        masInformacion: '',
        imagenGif: 'Piernas/Isquios.gif',
      },
      {
        nombreEjercicio: 'Vuelos frente poleas',
        tipoEjercicio: 'Hombros',
        repiticionesYSeries: '4x10',
        pesoUtilizado: '25kg??',
        masInformacion: '',
        imagenGif: 'Hombros/VuelosFrentePoleas.gif',
      },
      {
        nombreEjercicio: 'Prensa',
        tipoEjercicio: 'Piernas',
        repiticionesYSeries: '4x8',
        pesoUtilizado: '50kg',
        masInformacion: '',
        imagenGif: 'Piernas/Prensa.gif',
      },
      {
        nombreEjercicio: 'Abs bici',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x20',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: 'Abdominales/Bici.gif',
      },
      {
        nombreEjercicio: 'Abs elevaciones',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x20',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: '',
      },
      {
        nombreEjercicio: 'Rueda',
        tipoEjercicio: 'Abdominales',
        repiticionesYSeries: '3x10',
        pesoUtilizado: '',
        masInformacion: '',
        imagenGif: 'Abdominales/Rueda.gif',
      },
    ],
  },
];

export { arraygym };
